"""Add sender_id and receiver_id to messages

Revision ID: 04ec6be4cea0
Revises: b50173c7780d
Create Date: 2025-04-22 17:58:06.459340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04ec6be4cea0'
down_revision: Union[str, None] = 'b50173c7780d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sender_id', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('receiver_id', sa.Integer(), nullable=True))
    op.alter_column('messages', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_messages_recipient', table_name='messages')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'users', ['receiver_id'], ['id'])
    op.drop_column('messages', 'recipient')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('recipient', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_index('ix_messages_recipient', 'messages', ['recipient'], unique=False)
    op.alter_column('messages', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('messages', 'receiver_id')
    op.drop_column('messages', 'sender_id')
    # ### end Alembic commands ###
